#!/bin/bash
#
# KB-RAG Installation Script
#
# Installs KB-RAG system as systemd services on Debian/Ubuntu.
#
# Usage:
#   sudo ./install.sh [--user kb-rag] [--install-dir /opt/kb-rag]
#

set -euo pipefail

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Configuration
KB_USER="${KB_USER:-kb-rag}"
INSTALL_DIR="${INSTALL_DIR:-/opt/kb-rag}"
CONFIG_DIR="${INSTALL_DIR}/config"
DATA_DIR="${INSTALL_DIR}/data"
LOG_DIR="${INSTALL_DIR}/logs"
VENV_DIR="${INSTALL_DIR}/venv"

# Functions
log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

check_root() {
    if [[ $EUID -ne 0 ]]; then
        log_error "This script must be run as root"
        exit 1
    fi
}

check_os() {
    if [[ ! -f /etc/debian_version ]]; then
        log_error "This script requires Debian or Ubuntu"
        exit 1
    fi
    log_info "Detected Debian/Ubuntu system"
}

install_dependencies() {
    log_info "Installing system dependencies..."
    
    apt-get update -qq
    apt-get install -y \
        python3 \
        python3-pip \
        python3-venv \
        git \
        curl \
        sqlite3 \
        logrotate
    
    log_info "System dependencies installed"
}

create_user() {
    if id "$KB_USER" &>/dev/null; then
        log_warn "User $KB_USER already exists"
    else
        log_info "Creating user $KB_USER..."
        useradd --system --shell /bin/bash --create-home \
            --home-dir "$INSTALL_DIR" "$KB_USER"
        log_info "User $KB_USER created"
    fi
}

create_directories() {
    log_info "Creating directories..."
    
    mkdir -p "$INSTALL_DIR"
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$DATA_DIR"
    mkdir -p "$LOG_DIR"
    
    log_info "Directories created"
}

copy_files() {
    log_info "Copying application files..."
    
    # Get script directory
    SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
    
    # Copy application code
    rsync -av --exclude='.git' --exclude='__pycache__' \
        --exclude='*.pyc' --exclude='venv' --exclude='data' \
        "$SCRIPT_DIR/" "$INSTALL_DIR/"
    
    log_info "Application files copied"
}

setup_virtualenv() {
    log_info "Setting up Python virtual environment..."
    
    cd "$INSTALL_DIR"
    python3 -m venv "$VENV_DIR"
    source "$VENV_DIR/bin/activate"
    
    # Upgrade pip
    pip install --upgrade pip wheel setuptools
    
    # Install dependencies
    if [[ -f requirements.txt ]]; then
        pip install -r requirements.txt
    else
        log_error "requirements.txt not found"
        exit 1
    fi
    
    deactivate
    log_info "Virtual environment ready"
}

setup_configuration() {
    log_info "Setting up configuration..."
    
    # Create environment file if it doesn't exist
    if [[ ! -f "$CONFIG_DIR/kb-rag.env" ]]; then
        cat > "$CONFIG_DIR/kb-rag.env" <<'EOF'
# KB-RAG Configuration
# Generated by install.sh

# Embedding Configuration
EMBED_BACKEND=openai-compat
EMBED_MODEL=text-embedding-nomic-embed-text-v1.5-embedding
LMS_BASE_URL=http://localhost:1234

# Qdrant Configuration
QDRANT_HOST=localhost
QDRANT_PORT=6333
QDRANT_COLLECTION=kb_docs

# Cache Configuration
CACHE_BACKEND=lru
CACHE_MAX_SIZE_MB=512
CACHE_TTL=3600

# Batch Processing (FASE 8)
EMBED_BATCH_SIZE=32
FILE_BATCH_SIZE=50
QDRANT_BATCH_SIZE=100
HTTP_POOL_CONNECTIONS=20

# Health Server Configuration
HEALTH_HOST=0.0.0.0
HEALTH_PORT=8000

# Logging
LOG_LEVEL=INFO
LOG_PATH=/opt/kb-rag/logs/kb-rag.log
EOF
        log_info "Created default configuration: $CONFIG_DIR/kb-rag.env"
    else
        log_warn "Configuration file already exists, skipping"
    fi
}

install_systemd_services() {
    log_info "Installing systemd services..."
    
    # Copy service files
    cp "$INSTALL_DIR/deployment/systemd"/*.service \
        /etc/systemd/system/
    cp "$INSTALL_DIR/deployment/systemd"/*.target \
        /etc/systemd/system/
    
    # Reload systemd
    systemctl daemon-reload
    
    log_info "Systemd services installed"
}

setup_logrotate() {
    log_info "Setting up log rotation..."
    
    cat > /etc/logrotate.d/kb-rag <<EOF
$LOG_DIR/*.log {
    daily
    rotate 14
    compress
    delaycompress
    notifempty
    create 0640 $KB_USER $KB_USER
    sharedscripts
    postrotate
        systemctl reload kb-rag-server.service >/dev/null 2>&1 || true
    endscript
}
EOF
    
    log_info "Log rotation configured"
}

set_permissions() {
    log_info "Setting permissions..."
    
    chown -R "$KB_USER:$KB_USER" "$INSTALL_DIR"
    chmod -R 755 "$INSTALL_DIR/deployment/scripts"
    chmod 640 "$CONFIG_DIR/kb-rag.env"
    
    log_info "Permissions set"
}

enable_services() {
    log_info "Enabling services..."
    
    systemctl enable kb-rag-server.service
    systemctl enable kb-rag-health.service
    systemctl enable kb-rag.target
    
    log_info "Services enabled"
}

start_services() {
    log_info "Starting services..."
    
    systemctl start kb-rag.target
    
    # Wait for services to start
    sleep 5
    
    # Check status
    if systemctl is-active --quiet kb-rag-server.service; then
        log_info "✓ kb-rag-server.service is running"
    else
        log_error "✗ kb-rag-server.service failed to start"
        systemctl status kb-rag-server.service --no-pager
    fi
    
    if systemctl is-active --quiet kb-rag-health.service; then
        log_info "✓ kb-rag-health.service is running"
    else
        log_warn "✗ kb-rag-health.service failed to start"
    fi
}

print_summary() {
    cat <<EOF

${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}
${GREEN}  KB-RAG Installation Complete!${NC}
${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}

Installation Directory: $INSTALL_DIR
Configuration:         $CONFIG_DIR/kb-rag.env
Data Directory:        $DATA_DIR
Logs Directory:        $LOG_DIR

Services:
  - kb-rag-server     (MCP server)
  - kb-rag-health     (Health check HTTP server)
  - kb-rag-scheduler  (Job scheduler - placeholder)

Service Management:
  Start:    sudo systemctl start kb-rag.target
  Stop:     sudo systemctl stop kb-rag.target
  Restart:  sudo systemctl restart kb-rag.target
  Status:   sudo systemctl status kb-rag.target
  Logs:     sudo journalctl -u kb-rag-server -f

Health Check:
  curl http://localhost:8000/health

Next Steps:
  1. Edit configuration: $CONFIG_DIR/kb-rag.env
  2. Restart services: sudo systemctl restart kb-rag.target
  3. Test health: curl http://localhost:8000/health/detailed
  4. View logs: sudo journalctl -u kb-rag-server -f

${GREEN}━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━${NC}

EOF
}

# Main installation flow
main() {
    log_info "KB-RAG Installation Script"
    echo
    
    check_root
    check_os
    
    install_dependencies
    create_user
    create_directories
    copy_files
    setup_virtualenv
    setup_configuration
    install_systemd_services
    setup_logrotate
    set_permissions
    enable_services
    start_services
    
    print_summary
}

# Run main
main "$@"
